---
title: "Landings"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: FALSE
    code_folding: show
    number_sections: TRUE
---
    
# SET-UP
```{r markdwon, echo=F}
library(knitr)
opts_chunk$set(echo = T, collapse = T, fig.align = "center", fig.width = 9, fig.height = 6)
options(width = 120)
```    

## settings
```{r settings, message = F}
source('0.0_settings.R')
```

## load all data
```{r data, message = F}
load(paste0(dir.rdat, "catch.Rdata"))
```

# TABLES {.tabset}

## Total
```{r tabel total}
df <- catch
df[df$country!='Canada','country'] <- 'Foreign'
df <- ddply(df,c('year','country'),summarise,catch=sum(catch,na.rm=T))
df <- dcast(df,year~country,value.var = 'catch')
df[is.na(df)] <- 0
df$total <- with(df,Canada+Foreign)

kable(df,digits=0,row.names = FALSE, caption='Annual landings (t) within Canada’s Exclusive Economic Zone')

```

## Province
```{r tabel province}
df <- catch[catch$source=='ziff',]                                            # how did Thomas got provincial from 1985 onwards?
df <- ddply(df,c('year','prov'),summarise,catch=sum(catch,na.rm=T))
df <- dcast(df,year~prov,value.var = 'catch')
df$unknown <- NULL                                                            # not necessary for now

kable(df,digits=0,row.names = FALSE, caption='Annual landings (t) by province')

```

## NAFO
```{r table nafo}
df <- catch
df <- ddply(df,c('year','nafo'),summarise,catch=sum(catch,na.rm=T))
df <- dcast(df,year~nafo,value.var = 'catch',fill = 0)
df$'NA' <- NULL                                                            # not necessary for now

kable(df,digits=0,row.names = FALSE, caption='Annual landings (t) by NAFO division')

```